# Generated by Django 4.2.7 on 2023-11-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('idPartido', models.AutoField(primary_key=True, serialize=False)),
                ('cantPlayers', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('nameCancha', models.CharField(max_length=10)),
                ('nameGame', models.CharField(max_length=40)),
                ('p1', models.CharField(max_length=50)),
                ('p2', models.CharField(max_length=50)),
                ('p3', models.CharField(max_length=50)),
                ('p4', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.usuario')),
            ],
        ),
    ]
